sudo: required
language: c

env:
  global:
    # COVERITY_SCAN_TOKEN
    - secure: "NXwB/s0ZpQr0kJTESNxuVCrIVgX2ZsivmiODwK2LDFT1Nchdijd/Ope0cHb92FxURLcDetnl69EWlmLD5ROZQ5Qc+XakAdAEfy2ZrrCq14S9fSZzUtLB0wMW/GZ5hVneSnFmbprR3zQbTbcVvpTyvzDEr26Dd+HQNP0QQsOJ7B5kanLwKeiuNy437pjIOm7x4sjaylnA/b6FlV3a26C7eGN2ZiFCGT++9y3YlJAlxNlySSI+phRe0bihna/RygoYAs5efXefAuibEjtG5kL29cKMKzwEdXEFfDZcl0QYjkrAJqXUUC54YqIWnY56mhDzn0nfWIScQYth0ZS/vhteA8x+MYKFgGnqD9LBw+TsvRO3ZQ1iVrI5NBM6P2Ka6mAVv8OODN2EwWpwoqm2PJ36ZZ+2vJHBwHw10i3pDR48Fzw0x9Av6rkI5lS0hFLMogXtTaM2IlWu4VIevVRBICzrEz47LeOvJs17MZPYeOUhCFrG0ZP/8DR9nqJpmHVFA9FYcaalD/SXfDbBJTI+yV37mgfSM1zJ8tApPy4KOZ1wM2F0+COqEdxHqTJp2u9c1VQo1NegsYxxdB3mOYMLrTnAzQ5WOUdDezcFkAT+QE5WVhGUzpT4lzM1kVirJa2y3beh2i7uHfP2X+EtzJvWRbefJYQJNo8nYXXEwpdJ5v/0LyI="

addons:
  coverity_scan:
    project:
      name: "rcr/rirc"
      description: "Coverity scan of the static_analysis branch"
    notification_email: mail@rcr.io
    build_command_prepend: "make clean"
    build_command: "make -j2"
    branch_pattern: static_analysis

  apt: &apt
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precice-3.6

matrix:
  include:
    # gcc 4.9 on linux
    - env: C_COMPILER=gcc-4.9
      addons:
        apt:
          <<: *apt
          packages: gcc-4.9

    # clang 3.6 on linux
    - env: C_COMPILER=clang-3.6
      addons:
        apt:
          <<: *apt
          packages: clang-3.6

    # gcc 4.9 on osx
    - os: osx
      env: FORMULA=gcc49 COMPILER=gcc C_COMPILER=gcc-4.9

    # clang 3.6 on osx
    - os: osx
      osx_image: xcode6.4
      env: C_COMPILER=clang

before_install:
  - test "${TRAVIS_BRANCH}" != "static_analysis" -o "${TRAVIS_JOB_NUMBER##*.}" = "1" || exit 0
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" && "$COMPILER" == "gcc" ]]; then brew unlink gcc || true; fi' # ignore unlink errors
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" && "$COMPILER" == "gcc" ]]; then brew unlink $FORMULA || true; fi' # ignore unlink errors
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" && "$COMPILER" == "gcc" ]]; then brew install $FORMULA; fi'
  - export CC=$C_COMPILER

script:
  - test "${TRAVIS_BRANCH}" != "static_analysis" || exit 0
  - make && make test
